### ISSUE TITLE
QuestionXD

### ISSUE THREAD

**Issue by OkazakiNagisa** [ReddeR1337/PUBG-Radar#10]
I run this in offline mode directly after installation in win10 1703 x64 but fail.
Would you tell me what happened and how to solve that? I don't know java and kotlin at all!
Thanks!😂😂

D:\.Projects\18-3-8.pubg\pubg\PUBG-Radar-master>java -jar .\target\pubg-radar-1.0-SNAPSHOT-jar-with-dependencies.jar 192.168.137.1 PortFilter 192.168.137.39 ".\pu.pcap"
Loading PCAP File.
0
0
0
0
0
0
Exception in thread "main" java.lang.ExceptionInInitializerError
        at java.lang.J9VMInternals.ensureError(J9VMInternals.java:141)
        at java.lang.J9VMInternals.recordInitializationFailure(J9VMInternals.java:130)
        at pubg.radar.GameKt.main(Game.kt:51)
Caused by: java.util.NoSuchElementException: Collection contains no element matching the predicate.
        at pubg.radar.sniffer.Sniffer.<clinit>(Sniffer.kt:200)
        ... 1 more

**Comment by OkazakiNagisa** [comment]
C:\>java -version
java version "1.8.0"
Java(TM) SE Runtime Environment (build pwa6480sr4fp1-20170215_01(SR4 FP1))
IBM J9 VM (build 2.8, JRE 1.8.0 Windows 10 amd64-64 Compressed References 20170209_336038 (JIT enabled, AOT enabled)
J9VM - R28_20170209_0201_B336038
JIT  - tr.r14.java.green_20170125_131456
GC   - R28_20170209_0201_B336038_CMPRSS
J9CL - 20170209_336038)
JCL - 20170215_01 based on Oracle jdk8u121-b13

**Comment by aretazz1** [comment]
same mistake

**Comment by noise87** [comment]
use online batch

**Comment by lavy123** [comment]
i getting this
C:\Users\kunal\Downloads\PUBG-Radar-master (1)\PUBG-Radar-master>C:\Users\kunal\Downloads\PUBG-Radar-master (1)\PUBG-Radar-master -jar target\pubg-radar-1.0-SNAPSHOT-jar-with-dependencies.jar 192.168.2.2 PortFilter 192.168.2.3  1>java
'C:\Users\kunal\Downloads\PUBG-Radar-master' is not recognized as an internal or external command,
operable program or batch file.

**Comment by lavy123** [comment]
help plz

**Comment by HaoyeTang** [comment]
first, use the bat file provided, also make sure your drivers and VC++ are up to date
