### ISSUE TITLE
vpn help

### ISSUE THREAD

**Issue by noise87** [ReddeR1337/PUBG-Radar#11]
hi, and thx for work.
ok, i follow all steps for 2nd pc but my game pc can't connect to vpn...
the only thing i do different is for ip range, my gateway is 192.168.1.254 so i put "192.168.1.1 to 192.168.1.253" is right?

**Comment by Krypt0HaZe** [comment]
What is your defaut gateway ? 

 Try this https://imgur.com/a/AXh3Z

**Comment by noise87** [comment]
found error ^^
