### ISSUE TITLE
connect

### ISSUE THREAD

**Issue by lipeon** [ReddeR1337/PUBG-Radar#12]
cant conect in my vps, have onther way?

**Comment by noise87** [comment]
what problem with vpn?

**Comment by lipeon** [comment]
not conected, to other pc

**Comment by HaoyeTang** [comment]
why are you using a vps @lipeon

**Comment by lipeon** [comment]
Recomendation?

**Comment by lipeon** [comment]
Don't use on game pc or u will get banned!!!
