### ISSUE TITLE
Merge from AiYinZiLeGong

### ISSUE THREAD

**Issue by Sedoka** [ReddeR1337/PUBG-Radar#13]
Hello,

it would be great if you could merge changes about "items location" and "
player's direction" from  AiYinZiLeGong 's repo.

**Comment by aretazz1** [comment]
players direction is good in AiYinZiLeGong??

**Comment by HaoyeTang** [comment]
I don't know if AYZLG's player's direction is good but they were both written in Kotlin I think you can easily combine those two by yourself

**Comment by ReddeR1337** [comment]
https://github.com/ReddeR1337/PUBG-Radar/commit/b9aadd3cfbd4969d65099ee5e71badbc4b32d80d
