### ISSUE TITLE
Gray

### ISSUE THREAD

**Issue by LULz0** [ReddeR1337/PUBG-Radar#16]
hey everyone!

i follow  your install guide, then i start radar stuck on grey screen, how to fixit?
i'm using second pc 

sry for my english 👎

**Comment by Krypt0HaZe** [comment]
Join game

**Comment by aminermiss** [comment]
can we like help each other , i ll fix your grey screen if you install this one on my computer i can run other versions bvut not this one if you help me out i ll help you too

**Comment by Nytzo** [comment]
@aminermiss give ur discord userid

**Comment by aminermiss** [comment]
aminer#7992

**Comment by nengbowan** [comment]
@aminermiss  please agree , discord
