### ISSUE TITLE
Possible to Run in VirtualBox/Hyper-V?

### ISSUE THREAD

**Issue by kek777** [ReddeR1337/PUBG-Radar#18]
Hello,

I just want to ask, is this possible to run on VirtualBox / Hyper-V on the same pc. cuz i dont have 2nd pc.

thanks!

**Comment by jeremyholley2007** [comment]
Yep.

**Comment by HaoyeTang** [comment]
Absolutely

**Comment by kek777** [comment]
No ban risk right?

**Comment by HaoyeTang** [comment]
No ban risk.
