### ISSUE TITLE
what is these erors?

### ISSUE THREAD

**Issue by lavy123** [ReddeR1337/PUBG-Radar#22]
[WARNING]
[WARNING] Some problems were encountered while building the effective model for pubg:pubg-radar:jar:1.0-SNAPSHOT
[WARNING] 'dependencies.dependency.(groupId:artifactId:type:classifier)' must be unique: org.jetbrains.kotlin:kotlin-stdlib-jdk8:jar -> duplicate declaration of version ${kotlin.version} @ line 119, column 21
[WARNING]
[WARNING] It is highly recommended to fix these problems because they threaten the stability of your build.
[WARNING]
[WARNING] For this reason, future Maven versions might no longer support building such malformed projects.
[WARNING]

**Comment by lavy123** [comment]
[WARNING]
[WARNING] Some problems were encountered while building the effective model for pubg:pubg-radar:jar:1.0-SNAPSHOT
[WARNING] 'dependencies.dependency.(groupId:artifactId:type:classifier)' must be unique: org.jetbrains.kotlin:kotlin-stdlib-jdk8:jar -> duplicate declaration of version ${kotlin.version} @ line 119, column 21
[WARNING]
[WARNING] It is highly recommended to fix these problems because they threaten the stability of your build.
[WARNING]
[WARNING] For this reason, future Maven versions might no longer support building such malformed projects.
[WARNING]

**Comment by HaoyeTang** [comment]
Download the latest version of radar and maven and java then try to build again
