### ISSUE TITLE
how to fix this ! this is bat file

### ISSUE THREAD

**Issue by lavy123** [ReddeR1337/PUBG-Radar#23]
F:\pubg\PUBG-Radar-master>java -jar target\pubg-radar-1.0-SNAPSHOT-jar-with-dependencies.jar 192.168.2.2 PortFilter 192.168.2.3 Offline
Error: Unable to access jarfile target\pubg-radar-1.0-SNAPSHOT-jar-with-dependencies.jar

**Comment by HaoyeTang** [comment]
try to use the bat file provided by filling in the IPs
