### ISSUE TITLE
How to start it on vm?

### ISSUE THREAD

**Issue by askedo** [ReddeR1337/PUBG-Radar#25]
I did everything as instructed. I got 3 files. how to run them? when I run the bat file it opens and closes immediately. nothing happens. Help please!

**Comment by HaoyeTang** [comment]
you have to edit the bat file and filling in the game pc IP and cheat pc IP

**Comment by askedo** [comment]
Ok now i have grey screen and nothing else. also i have a AL lib: (EE) ALCmmdevPlayback_open: Device init failed: 0x80070490 in bat file. What was that?

**Comment by ReddeR1337** [comment]
https://github.com/ReddeR1337/PUBG-Radar/issues/30
