### ISSUE TITLE
Player's view direction rather moving direction

### ISSUE THREAD

**Issue by HaoyeTang** [ReddeR1337/PUBG-Radar#26]
the map displays the direction that the player is moving to rather looking at, I believe it'll be better if you can let us see the direction that the player is looking at

**Comment by HaoyeTang** [comment]
@ReddeR1337

**Comment by XvenDeR** [comment]
> Get self player's location by parsing CharMoveComp RPC. So the player's direction is corrected now.

I'm not sure does ReddeR1337 uses this, so u can try.

**Comment by HaoyeTang** [comment]
I don't know much about coding can you help me @XvenDeR

**Comment by pubgrad** [comment]
@HaoyeTang Just use xvender fork it has the fix

**Comment by XvenDeR** [comment]
Yes, you can try out my fork.

**Comment by ReddeR1337** [comment]
https://github.com/ReddeR1337/PUBG-Radar/commit/b9aadd3cfbd4969d65099ee5e71badbc4b32d80d
