### ISSUE TITLE
Strange error in Hyper-V

### ISSUE THREAD

**Issue by kek777** [ReddeR1337/PUBG-Radar#28]
Strange error, can you guys please help me? thanks!

![dds](https://user-images.githubusercontent.com/36532137/37251595-2c5feae0-254e-11e8-81f6-506318e8b1d9.png)

**Comment by malakazzz0** [comment]
lol same

**Comment by glowgvng** [comment]
@kek777 @malakazzz0 3rd line down states it buddy you NEED openGL support 3.3 for this to work

**Comment by malakazzz0** [comment]
@glowgvng hyper v default opengl version 1.1 how can i change 3.3v ??plz help us

**Comment by glowgvng** [comment]
@malakazzz0  list me your specs please

**Comment by kek777** [comment]
@glowgvng i think i need to install some nvidia drivers on my Hyper-v

**Comment by kek777** [comment]
@glowgvng how do i get that opengl 3.3 in hyper v?
im on i7 and gtx titan (old version)

**Comment by malakazzz0** [comment]
![sscapture](https://user-images.githubusercontent.com/34477675/37271768-8b8f8d98-2591-11e8-862b-7ff8b559680a.JPG)

**Comment by malakazzz0** [comment]
trying to change system32 opengl32.dll but nothing happens :(((

**Comment by malakazzz0** [comment]
i m already use  compile pubg.jar with vmware $##### BE detect VM ware $$##### didnt work vmbox ,,,then try hyper $##

**Comment by ReddeR1337** [comment]
RemoteFX
