### ISSUE TITLE
Add new fixes from AiYinZiLeGong radar

### ISSUE THREAD

**Issue by pubgrad** [ReddeR1337/PUBG-Radar#29]
Can you please add new fixes to your radar from AiYinZiLeGong one? He fixed player view, item position, item disappear after pickup and added weapon, distance and health of enemy players.

The reason I am asking is your radar works fine but his radar on my pc shows black screen. I have even tried older versions of his and they also show black screen I dont know why.

Thanks

**Comment by EiTeR94** [comment]
You can do it by youself, it’s just some line to modify
