### ISSUE TITLE
AL lib: (EE) ALCmmdevPlayback_open: Device init failed: 0x80070490

### ISSUE THREAD

**Issue by midi2** [ReddeR1337/PUBG-Radar#30]
did anyone have the same problem?

it only show grey screen (im using vpn)

please help thanks

**Comment by glowgvng** [comment]
while in game keep it open and press T / talk in game then tell me if still grey screen

**Comment by ReddeR1337** [comment]
i have no idea

**Comment by ReddeR1337** [comment]
2nd pc or VM ?
PC spec ?

**Comment by sinister-gomofob** [comment]
Same shit on Virtualbox

**Comment by whitewingz2017** [comment]
if you are using virtual make it sure it is bridge network

**Comment by kek777** [comment]
same issue bruh

**Comment by sinister-gomofob** [comment]
> if you are using virtual make it sure it is bridge netwo

Of course its brigde

**Comment by midi2** [comment]
I used 2 PC, it was working fine and suddenly out of blue it is not working,  I am play till the end of the game and still no map coming out on the gray screen.

so i try another PC (for this radar), fresh install everything, it comes without error (show 0) and then only gray screen appears, no map shown up.

my gaming PC using 
AMD FX 8350 with 16GB RAM and Nvidia 660Ti

for Radar using the same CPU with 8gb of RAM and Nvidia 660Ti too
