### ISSUE TITLE
New update

### ISSUE THREAD

**Issue by pubgrad** [ReddeR1337/PUBG-Radar#31]
Soon the new update on test server will be implemented on live servers. Will the radar work or that will be the end?

**Comment by XvenDeR** [comment]
Should work if they don't encrypt packets.

**Comment by ReddeR1337** [comment]
https://github.com/ReddeR1337/PUBG-Radar/commit/b9aadd3cfbd4969d65099ee5e71badbc4b32d80d

**Comment by ReddeR1337** [comment]
After update we will see
