### ISSUE TITLE
config.useVsync(false) causes a lot of extra gpu resources 

### ISSUE THREAD

**Issue by dangelization** [ReddeR1337/PUBG-Radar#35]
in
https://github.com/ReddeR1337/PUBG-Radar/blob/master/src/main/kotlin/pubg/radar/ui/GLMap.kt#L116
this line causes computer GPU 3D to be running at very high, even if game is not running.
I initially thought this radar has some hidden miner running that causes the gpu to run at huge load, however after removing the line gpu usage falls back down.

**Comment by ReddeR1337** [comment]
If i remove config.useVsync (false) java eat more memory and cpu for me
:|
