### ISSUE TITLE
How to donate? 

### ISSUE THREAD

**Issue by EpicGamer123** [ReddeR1337/PUBG-Radar#36]
I realize this hack is public, and free, but considering it's being updated and works SO well, and I'm sure a lot of time and effort went into this hack, is there any way I can donate some money? I'm sorry if this is the wrong place to ask this, but I don't see a PM system to contact ReddeR directly, and I also don't see a general comment section.

**Comment by DMKISSMYASS** [comment]
Is work for you ?

**Comment by EpicGamer123** [comment]
Well, I'm at work and haven't  been on since before the update, but no I don't think it's working right now, but ReddeR is already working on an update. Besides, I got to use it for a while before the new update broke it.

**Comment by midi2** [comment]
I willing to do that as well but currently mine is not working :( but still

**Comment by EpicGamer123** [comment]
Yea the update today broke it. I'm sure ReddeR will get it working again.

Glad to see others are willing to donate as well.

**Comment by dcg7058** [comment]
我也愿意     你们能看懂中文？哈哈

**Comment by ReddeR1337** [comment]
after update, I'll think about it
