### ISSUE TITLE
why  lost the first actor creation bunch.just create as we need it

### ISSUE THREAD

**Issue by MrRemix1** [ReddeR1337/PUBG-Radar#37]
lost the first actor creation bunch.just create as we need it

**Comment by EiTeR94** [comment]
do you know how to read ? 
redder said on the README 

"Don't use radar after this patch (wait for upd):

https://twitter.com/PUBG_help/status/973194202283692032"

**Comment by pubgrad** [comment]
Yeah I am waiting for an update too. Once you get used to radar its harder to play without it
