### ISSUE TITLE
PUBG after the update, if it had been in

### ISSUE THREAD

**Issue by qishao47** [ReddeR1337/PUBG-Radar#38]
PUBG after the update, if it had been in

**Comment by EiTeR94** [comment]
Don't use radar after this patch (wait for upd):

https://twitter.com/PUBG_help/status/973194202283692032

**Comment by qishao47** [comment]
Don't use? I have update is complete.

**Comment by EiTeR94** [comment]
please, read, stop be stupid. the radar is not working ATM because of the update.

**Comment by qishao47** [comment]
I'm sorry, I saw it wrong
Thank you very much!

**Comment by ReddeR1337** [comment]
just wait upd
