### ISSUE TITLE
vmviwer question

### ISSUE THREAD

**Issue by 13330863440** [ReddeR1337/PUBG-Radar#39]
![20180313000650](https://user-images.githubusercontent.com/30033972/37356131-469e3ed8-2720-11e8-8530-15006d398b6d.jpg)
提醒一下，在虚拟机中会有如图提示。可能需要隐藏虚拟机进程。
may need to hide the process.
It's just a hint.

**Comment by EiTeR94** [comment]
or just use a second PC

**Comment by pubgpubgpubg** [comment]
anyway radar now dont work

**Comment by ReddeR1337** [comment]
vmware in battleeye blacklist
radar isn't working yet
