### ISSUE TITLE
Grey screen with Xbox

### ISSUE THREAD

**Issue by b000sh** [ReddeR1337/PUBG-Radar#40]
Im pretty sure I got everything working, but all im getting is a grey screen when trying with an xbox.

any idea what im doing wrong?

**Comment by Anon1984** [comment]
How strange. Did you read this? [Readme](https://github.com/ReddeR1337/PUBG-Radar/blob/master/README.md) the first line can help

**Comment by b000sh** [comment]
What line?

**Comment by schulzjona** [comment]
the first

**Comment by b000sh** [comment]
I'm not seeing anything relevant to using this on Xbox. We haven't had an update lately, so again, not sure what I'm missing here.

**Comment by b000sh** [comment]
I guess I thought I've read people still being able to use it on Xbox, must have heard wrong. We are way behind the PC version, so not sure what changed.
