### ISSUE TITLE
уменьшить количество предметов в фильтрах

### ISSUE THREAD

**Issue by rogiki** [ReddeR1337/PUBG-Radar#43]
Привет! @ReddeR1337 

Подскажи, где можно подправить фильтры итемов? например выкинуть из отображения неактуальное оружие или эквип?

**Comment by ReddeR1337** [comment]
https://github.com/ReddeR1337/PUBG-Radar/blob/master/src/main/kotlin/pubg/radar/ui/Icons.kt
Ненужные строчки закоменти и все
