### ISSUE TITLE
526 lost the first actor creation bunch. just create as we need it

### ISSUE THREAD

**Issue by 157688302** [ReddeR1337/PUBG-Radar#44]
the radar camera can't follow me

**Comment by xXSkrill1337** [comment]
Try this https://github.com/Jerry1211/RadarProject

**Comment by 157688302** [comment]
it also bad... same problem

**Comment by 157688302** [comment]
always tips "lost the first actor creation bunch. just create as we need it"

**Comment by linnnnnnnn** [comment]
can you fixed？
