### ISSUE TITLE
Work Perfectly But Grey screen on 2ºPC

### ISSUE THREAD

**Issue by alantody** [ReddeR1337/PUBG-Radar#45]
Error in console: AL lib: (EE) ALCmmdevPlayback_open: Device init failed: 0x80070490

http://prntscr.com/is7wtw

**Comment by dragonholi** [comment]
have the same error. but radar work fine. any solutions how fix this error?

**Comment by linnnnnnnn** [comment]
+1

**Comment by ReddeR1337** [comment]
try use 4k map
