### ISSUE TITLE
Discord link doesn't work

### ISSUE THREAD

**Issue by VeoMorphine** [ReddeR1337/PUBG-Radar#46]
Discord link is broken

**Comment by L-KE** [comment]
Don't think it is, I clicked on it and it worked

**Comment by ReddeR1337** [comment]
+1, worked fine for me

**Comment by VeoMorphine** [comment]
o_O Can someone see why I was banned then? I don't think I broke any rules, and I was helping someone get a packet capture done so I could try to implement xbox support.

**Comment by VeoMorphine** [comment]
![image](https://user-images.githubusercontent.com/37481618/37558902-f8be3572-29f1-11e8-8bd8-0a4ff5d38cfa.png)
Brand new account and still getting link expired.

**Comment by CrimsonPrince** [comment]
Discord bans are by IP not account that's why.

**Comment by Cyphershoot** [comment]
Same here :( i dont know why
