### ISSUE TITLE
Map not show please help.

### ISSUE THREAD

**Issue by jj4997** [ReddeR1337/PUBG-Radar#47]
![image](https://user-images.githubusercontent.com/37490433/37561538-2d109cf2-2a83-11e8-8cef-c86d76e9c0fd.png)
When i've start .bat file. it's show these msg.
but it's can shows the weapons and player correctly but it's not have map.
![image](https://user-images.githubusercontent.com/37490433/37561556-c3282b4c-2a83-11e8-910d-2fe0dfcb9589.png)

**Comment by jj4997** [comment]
i've already install GA and  selectDirect3D support when installed already.

**Comment by linnnnnnnn** [comment]
+1

**Comment by lu03797** [comment]
Whether the environment variable is called correctly

**Comment by jyu25utk** [comment]
You install the wrong version of guest addition, try to download the latest guest addition and solve the problem.

**Comment by jyu25utk** [comment]
@jj4997

**Comment by dragonholi** [comment]
install GA 5.2.8 safe mode, select Direct3D. next menu  press **NO**, then next next restart pc. Problex is here

**Comment by mendeel** [comment]
I'm having the same problem here but I don't get these console errors, just can't see the background map. And I'm running on a 2nd pc.

**Comment by ReddeR1337** [comment]
try use 4k map

**Comment by mendeel** [comment]
No luck :( Tried compiling with JDK9.0.4 and running with JRE 8 U161
