### ISSUE TITLE
AMD GPU OpenGL Version 

### ISSUE THREAD

**Issue by Kevla1994** [ReddeR1337/PUBG-Radar#5]
ERROR: error(#272) Implicit version number 110 not supported by GL3 forward compatible context
ERROR: error(#273) 1 compilation errors.  No code generated

Can't get it working on a my second pc... i am using a AMD6850X2 GPU

**Comment by ReddeR1337** [comment]
amd\ati radeon cant run opengl xD
Idk how fix that

**Comment by aretazz1** [comment]
buy new gpu?

**Comment by Kevla1994** [comment]
for sure i will buy a new gpu :D 

http://www.java-gaming.org/topics/how-to-force-opengl-version/35103/view.html 
might be the solution but i don't know how to use it :D

**Comment by ReddeR1337** [comment]
@Kevla1994 @aretazz1 try redownload repo, mb i fix that

**Comment by Kevla1994** [comment]
i appreciate ur investigations but it didnt fix it :/

**Comment by ReddeR1337** [comment]
:cry:
