### ISSUE TITLE
GLFW_PLATFORM_ERROR error (D3D support installed)

### ISSUE THREAD

**Issue by testman123123** [ReddeR1337/PUBG-Radar#51]
VB 5.2.8 GA 5.2.8
Installed D3d support in safe mode.
virtual machine
4 cpu cores (ryzen)
4gb ram
256mb vram
GPU accellerations on
windows 7 x64 ult

C:\App>archive\RadarProject.exe "192.168.0.238" PortFilter "192.168.0.234"
0
[LWJGL] GLFW_PLATFORM_ERROR error
        Description : WGL: Failed to make context current
        Stacktrace  :
                org.lwjgl.glfw.GLFW.glfwMakeContextCurrent(GLFW.java:3318)
                com.badlogic.gdx.backends.lwjgl3.Lwjgl3Window.makeCurrent(Lwjgl3
Window.java:429)
                com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.loop(Lwjgl3Ap
plication.java:133)
                com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.<init>(Lwjgl3
Application.java:110)
                main.ui.GLMap.show(GLMap.kt:120)
                main.GameKt.main(Game.kt:59)
OpenGL Warning: GetRandomRgn returned (-1) instead of (1), VisibleRegions update
 failed

**Comment by yazhog** [comment]
same problem

**Comment by RxZoid24** [comment]
Same

**Comment by ReddeR1337** [comment]
Try restart bat
