### ISSUE TITLE
GetRandomRgn returned (-1) problem!

### ISSUE THREAD

**Issue by RxZoid24** [ReddeR1337/PUBG-Radar#52]
I'm having this problem.
![screenshot_213](https://user-images.githubusercontent.com/37559969/37626548-372c9916-2baf-11e8-950e-f4f5648c2b87.png)
map is grey and console is showing this message. Direct3D support is installed. What is causing this problem?

**Comment by ReddeR1337** [comment]
i can ignore warning msg
Try use 4k map

**Comment by RxZoid24** [comment]
The version I was using is outdated. Now everything works ty
