### ISSUE TITLE
Running on second pc

### ISSUE THREAD

**Issue by sdkrocks** [ReddeR1337/PUBG-Radar#61]
When running the radar on a second computer with a VPN, do I use the IPs assigned from the router to each computer, or do I use the ones that the VPN assigned.
ex:

Router:
     gaming pc: 192.168.0.9
     radar comp: 192.168.0.15

OR

VPN (ppp adapter)
     gaming pc: 192.168.0.3
     radar comp: 192.168.0.2

**Comment by ryan19629** [comment]
You would use Radar: 192.168.0.5 Gaming: 192.168.0.3
