### ISSUE TITLE
Teammates are drawn in red, just like enemies.

### ISSUE THREAD

**Issue by DeveloperUnknown** [ReddeR1337/PUBG-Radar#63]
Fixed in pull request #55

**Comment by furioussoul** [comment]
same situation though author fixed it before , still have this bug now

**Comment by DeveloperUnknown** [comment]
I don't understand why he is ignoring pull requests.

**Comment by the7thway** [comment]
teammates color sometime are blue,,sometime are red...

**Comment by DeveloperUnknown** [comment]
Guys. The fix is in the damn pull request.
