### ISSUE TITLE
Map not showing

### ISSUE THREAD

**Issue by pabelnl** [ReddeR1337/PUBG-Radar#65]
The map is not showing while running the radar on a second PC.

No logs at all.

Running Windows 8.1 x64 virtual machine with VMWARE Fusion 10.1.1 on a MacBook Pro 15' 2017
JDK-8U162 WINDOWS X64
apache maven 3.5.3

**Comment by ReddeR1337** [comment]
https://github.com/ReddeR1337/PUBG-Radar#if-you-have-glfw_platform_error-try-this
