### ISSUE TITLE
Second PC map is grey

### ISSUE THREAD

**Issue by dragonholi** [ReddeR1337/PUBG-Radar#68]
Hello redder, i use ur old version, and all is working correctly but all new releases is not working.

Just download ur last version, build change IP, start- and grey map no errors. i saw enemys but dont see map.

I was trying run 4kmap bat, then rebuild, and i got error after
![o0wvq-r0a40](https://user-images.githubusercontent.com/37455128/37776883-544ef81e-2df7-11e8-8ff8-a2dcb579eccf.jpg)

Older version is work fine, хз почему

**Comment by pabelnl** [comment]
Happens to me too, old version works fine.

No errors for me.

<img width="1281" alt="screenshot_2" src="https://user-images.githubusercontent.com/19191505/37789511-57962190-2dc1-11e8-954a-37f4bdca8314.png">
