### ISSUE TITLE
Faggots who sell this repo

### ISSUE THREAD

**Issue by ReddeR1337** [ReddeR1337/PUBG-Radar#9]
If you have links just leave them here.

https://plati.ru/itm/privatnye-chity-dlja-pubg-multihack-chit-radar-128293/2427785

**Comment by XKReSycj** [comment]
are you kidding??

- Copy source code from AiYinZiLeGong/PUBG-Radar and Jerry1211‘s fork .
- Let others do not know that this repo from fork.
- Remove all commits from other contributors .  
- There is no any thanks to the previous developer.


**You are already stealing.**

Any changes you make to LICENSE are invalid. The copyright of this code does not belong to you.

**Comment by ReddeR1337** [comment]
@XKReSycj I'm not saying that I did everything, but selling public code is idiocy
Developers of this is @AiYinZiLeGong, @Jerry1211, @SamuelNZ and many others ppl

Some idiots sell it, others idiots buy it
Why work other people who did it free on github brings profit to scammers?
